ci: fix cram tests on Windows
This commit contains a patch for cram to fix an environment encoding issue:
TypeError: environment can only contain strings

Cram tests should be executed by `meson devenv`, because meson does not
seem to add rpath entries on Windows.